### ISSUE TITLE
This rule should be supported 

### ISSUE THREAD

**Issue by aliang8** [semantic-math/math-rules#37]
```
export const DISTRIBUTE_NTH_ROOT = defineRuleString(
    'nthRoot(#a_0 * ...)', 'nthRoot(#a_0) * ...'
)
```
#35

**Comment by k4b7** [comment]
I'm reopening this b/c I'd like use to be able to implement it the way it's described above.

**Comment by aliang8** [comment]
It is. I changed it in my new commits. :D

**Comment by k4b7** [comment]
Cool... I'll have a look.  We can close it after the PR lands. :)
