### ISSUE TITLE
COMBINE_UNDER_ROOT rule pattern 

### ISSUE THREAD

**Issue by aliang8** [semantic-math/math-rules#38]
```
export const COMBINE_UNDER_ROOT = 
defineRuleString('nthRoot(#a_0, #c) * ...', 'nthRoot(#a_0 * ..., #c)')
```

 `e.g. nthRoot(2, 2) * nthRoot(3, 2) -> nthRoot(2 * 3, 2)`

This rule should be supported. 
#35

**Comment by k4b7** [comment]
I'm reopening this b/c we should be able to support it the way it's described above.
